#! /bin/bash

# Flush
iptables -F
iptables -X
iptables -Z
iptables -t nat -F

# Default rules
iptables -P INPUT ACCEPT
iptables -P OUTPUT ACCEPT
iptables -P FORWARD ACCEPT

# Setting up the virtual network
ifconfig xenbr0 10.0.0.1 up
echo 1 > /proc/sys/net/ipv4/ip_forward

# NAT
iptables -A FORWARD -i xenbr0 -j ACCEPT
iptables -t nat -A POSTROUTING -o eno1 -j MASQUERADE

# Access to services
iptables -t nat -A PREROUTING -i eno1 -p tcp --dport 80 -s 192.168.73.47 -j DNAT --to 10.0.0.2:80		# HTTP
iptables -t nat -A PREROUTING -i eno1 -p tcp --dport 21 -s 192.168.73.47 -j DNAT --to 10.0.0.6:21		# FTP
iptables -t nat -A PREROUTING -i eno1 -p tcp --dport 8080 -s 192.168.73.47 -j DNAT --to 10.0.0.5:80	# WebDAV

# Redirect to 192.168.73.46
iptables -t nat -A PREROUTING -i eno1 -p tcp --dport 80 -j DNAT --to 192.168.73.46:80			# HTTP
iptables -t nat -A PREROUTING -i eno1 -p tcp --dport 21 -j DNAT --to 192.168.73.46:21			# FTP
iptables -t nat -A PREROUTING -i eno1 -p tcp --dport 8080 -j DNAT --to 192.168.73.46:8080	# WebDAV