#! /bin/bash

# Flush
iptables -F
iptables -X
iptables -Z
iptables -t nat -F

# Default rules
iptables -P INPUT ACCEPT
iptables -P OUTPUT ACCEPT
iptables -P FORWARD ACCEPT

# Setting up the virtual network
ifconfig xenbr0 10.0.0.1 up
echo 1 > /proc/sys/net/ipv4/ip_forward
